#!/bin/bash

if ! ps -ef | grep nginx | grep master > /dev/null; then
  echo "service (init) says that nginx is not running"
else
  echo "Nginx process seems to be running, but service status might be outdated"
fi

echo  # Add an empty line at the end
